[book]
title = "Yasser Muayed"
authors = ["Yasser Muayed"]
description = "Yasser Muayed's Study Notes"
language = "en"
multilingual = false
src = "src"

[output.html]
no-section-label = true

[output.html.print]
enable = false

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding


[output.html.redirect]
"/link/memory-game.html" = "http://memory-game-test.pages.dev/"
"/other-installation-methods.html" = "../infra/other-installation-methods.html"
